# --coding:utf-8--
import turtle

turtle.clear()
turtle.hideturtle()
turtle.delay(0)
turtle.bgcolor("red")
turtle.color("yellow")
turtle.fillcolor("Yellow")
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.setpos(0,50)
turtle.pendown()
for x in range(10):
    turtle.begin_fill()
    turtle.fillcolor("Green")
    turtle.circle(50)
    turtle.end_fill()
    turtle.delay(10)
    turtle.begin_fill()
    turtle.fillcolor("Black")
    turtle.circle(50)
    turtle.end_fill()
turtle.penup()
turtle.setpos(40,40)
turtle.write("Animation Done")
turtle.home()
turtle.showturtle()
turtle.mainloop()
